# Generated by Django 4.2 on 2023-04-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='D:\\Projects\\portfolio\\static\\img'),
        ),
    ]
